// Code generated by go-swagger; DO NOT EDIT.

package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/phoax/godemo/models"
)

// GetBlockNumberOKCode is the HTTP code returned for type GetBlockNumberOK
const GetBlockNumberOKCode int = 200

/*GetBlockNumberOK block number

swagger:response getBlockNumberOK
*/
type GetBlockNumberOK struct {

	/*
	  In: Body
	*/
	Payload *models.NetworkBlockNumber `json:"body,omitempty"`
}

// NewGetBlockNumberOK creates GetBlockNumberOK with default headers values
func NewGetBlockNumberOK() *GetBlockNumberOK {

	return &GetBlockNumberOK{}
}

// WithPayload adds the payload to the get block number o k response
func (o *GetBlockNumberOK) WithPayload(payload *models.NetworkBlockNumber) *GetBlockNumberOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get block number o k response
func (o *GetBlockNumberOK) SetPayload(payload *models.NetworkBlockNumber) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlockNumberOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetBlockNumberDefault Internal error

swagger:response getBlockNumberDefault
*/
type GetBlockNumberDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBlockNumberDefault creates GetBlockNumberDefault with default headers values
func NewGetBlockNumberDefault(code int) *GetBlockNumberDefault {
	if code <= 0 {
		code = 500
	}

	return &GetBlockNumberDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get block number default response
func (o *GetBlockNumberDefault) WithStatusCode(code int) *GetBlockNumberDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get block number default response
func (o *GetBlockNumberDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get block number default response
func (o *GetBlockNumberDefault) WithPayload(payload *models.Error) *GetBlockNumberDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get block number default response
func (o *GetBlockNumberDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBlockNumberDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
