// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/phoax/godemo/models"
)

// GetAccountBalanceCreatedCode is the HTTP code returned for type GetAccountBalanceCreated
const GetAccountBalanceCreatedCode int = 201

/*GetAccountBalanceCreated transfer

swagger:response getAccountBalanceCreated
*/
type GetAccountBalanceCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Ack `json:"body,omitempty"`
}

// NewGetAccountBalanceCreated creates GetAccountBalanceCreated with default headers values
func NewGetAccountBalanceCreated() *GetAccountBalanceCreated {

	return &GetAccountBalanceCreated{}
}

// WithPayload adds the payload to the get account balance created response
func (o *GetAccountBalanceCreated) WithPayload(payload *models.Ack) *GetAccountBalanceCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get account balance created response
func (o *GetAccountBalanceCreated) SetPayload(payload *models.Ack) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountBalanceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetAccountBalanceDefault Internal error

swagger:response getAccountBalanceDefault
*/
type GetAccountBalanceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAccountBalanceDefault creates GetAccountBalanceDefault with default headers values
func NewGetAccountBalanceDefault(code int) *GetAccountBalanceDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAccountBalanceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get account balance default response
func (o *GetAccountBalanceDefault) WithStatusCode(code int) *GetAccountBalanceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get account balance default response
func (o *GetAccountBalanceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get account balance default response
func (o *GetAccountBalanceDefault) WithPayload(payload *models.Error) *GetAccountBalanceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get account balance default response
func (o *GetAccountBalanceDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountBalanceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
