// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/phoax/godemo/models"
)

// NewSetTransferParams creates a new SetTransferParams object
// no default values defined in spec.
func NewSetTransferParams() SetTransferParams {

	return SetTransferParams{}
}

// SetTransferParams contains all the bound params for the set transfer operation
// typically these are obtained from a http.Request
//
// swagger:parameters setTransfer
type SetTransferParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Transfer to address
	  Required: true
	  In: body
	*/
	To *models.To
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSetTransferParams() beforehand.
func (o *SetTransferParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.To
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("to", "body", ""))
			} else {
				res = append(res, errors.NewParseError("to", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.To = &body
			}
		}
	} else {
		res = append(res, errors.Required("to", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
