// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Piggy Breaker
//
//  Piggy Breaker is a game built on blockchain technology.
//  You can securely play with Ether to get a chance to break the piggy!
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api
//  Version: 0.0.1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
