// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Piggy Breaker is a game built on blockchain technology.\nYou can securely play with Ether to get a chance to break the piggy!\n",
    "title": "Piggy Breaker",
    "version": "0.0.1"
  },
  "basePath": "/api",
  "paths": {
    "/": {
      "get": {
        "tags": [
          "Homepage"
        ],
        "summary": "Homepage",
        "operationId": "homepage",
        "responses": {
          "200": {
            "description": "homepage response",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "201": {
            "description": "Created"
          },
          "default": {
            "description": "user validation error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/network/blockNumber": {
      "get": {
        "description": "\u003cb\u003eGet blockchain block number\u003c/b\u003e",
        "tags": [
          "Network"
        ],
        "summary": "Get block number",
        "operationId": "getBlockNumber",
        "parameters": [
          {
            "type": "integer",
            "description": "Game id",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Notify confirmation",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Ack": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "NetworkBlocNumber": {
      "description": "BlockNumber",
      "type": "object",
      "properties": {
        "blockNumber": {
          "description": "\u003cb\u003eBlockNumber\u003c/b\u003e",
          "type": "integer"
        }
      }
    },
    "Principal": {
      "type": "string"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Piggy Breaker is a game built on blockchain technology.\nYou can securely play with Ether to get a chance to break the piggy!\n",
    "title": "Piggy Breaker",
    "version": "0.0.1"
  },
  "basePath": "/api",
  "paths": {
    "/": {
      "get": {
        "tags": [
          "Homepage"
        ],
        "summary": "Homepage",
        "operationId": "homepage",
        "responses": {
          "200": {
            "description": "homepage response",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "201": {
            "description": "Created"
          },
          "default": {
            "description": "user validation error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/network/blockNumber": {
      "get": {
        "description": "\u003cb\u003eGet blockchain block number\u003c/b\u003e",
        "tags": [
          "Network"
        ],
        "summary": "Get block number",
        "operationId": "getBlockNumber",
        "parameters": [
          {
            "type": "integer",
            "description": "Game id",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Notify confirmation",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Ack": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "NetworkBlocNumber": {
      "description": "BlockNumber",
      "type": "object",
      "properties": {
        "blockNumber": {
          "description": "\u003cb\u003eBlockNumber\u003c/b\u003e",
          "type": "integer"
        }
      }
    },
    "Principal": {
      "type": "string"
    }
  }
}`))
}
