// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Godemo is a Golang code demo.\n",
    "title": "Godemo",
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "tags": [
          "Homepage"
        ],
        "summary": "Homepage",
        "operationId": "homepage",
        "responses": {
          "200": {
            "description": "homepage response",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "user validation error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/account/balance/{address}": {
      "get": {
        "description": "\u003cb\u003eGet account balance\u003c/b\u003e",
        "tags": [
          "Account"
        ],
        "summary": "Get account balance",
        "operationId": "getAccountBalance",
        "parameters": [
          {
            "type": "string",
            "description": "address to get balance",
            "name": "address",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "transfer",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/account/transfer": {
      "post": {
        "description": "\u003cb\u003eSet a transfer\u003c/b\u003e",
        "tags": [
          "Account"
        ],
        "summary": "Set a transfer",
        "operationId": "setTransfer",
        "parameters": [
          {
            "description": "Transfer to address",
            "name": "to",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/To"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "transfer",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/network/block-number": {
      "get": {
        "description": "\u003cb\u003eGet blockchain block number\u003c/b\u003e",
        "tags": [
          "Network"
        ],
        "summary": "Get block number",
        "operationId": "getBlockNumber",
        "responses": {
          "200": {
            "description": "block number",
            "schema": {
              "$ref": "#/definitions/NetworkBlockNumber"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Ack": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "NetworkBlockNumber": {
      "description": "BlockNumber",
      "type": "object",
      "properties": {
        "blockNumber": {
          "description": "\u003cb\u003eBlockNumber\u003c/b\u003e",
          "type": "integer"
        }
      }
    },
    "Principal": {
      "type": "string"
    },
    "To": {
      "description": "To address",
      "type": "object",
      "properties": {
        "address": {
          "description": "\u003cb\u003eaddress\u003c/b\u003e",
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Godemo is a Golang code demo.\n",
    "title": "Godemo",
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "tags": [
          "Homepage"
        ],
        "summary": "Homepage",
        "operationId": "homepage",
        "responses": {
          "200": {
            "description": "homepage response",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "user validation error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/account/balance/{address}": {
      "get": {
        "description": "\u003cb\u003eGet account balance\u003c/b\u003e",
        "tags": [
          "Account"
        ],
        "summary": "Get account balance",
        "operationId": "getAccountBalance",
        "parameters": [
          {
            "type": "string",
            "description": "address to get balance",
            "name": "address",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "transfer",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/account/transfer": {
      "post": {
        "description": "\u003cb\u003eSet a transfer\u003c/b\u003e",
        "tags": [
          "Account"
        ],
        "summary": "Set a transfer",
        "operationId": "setTransfer",
        "parameters": [
          {
            "description": "Transfer to address",
            "name": "to",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/To"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "transfer",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/network/block-number": {
      "get": {
        "description": "\u003cb\u003eGet blockchain block number\u003c/b\u003e",
        "tags": [
          "Network"
        ],
        "summary": "Get block number",
        "operationId": "getBlockNumber",
        "responses": {
          "200": {
            "description": "block number",
            "schema": {
              "$ref": "#/definitions/NetworkBlockNumber"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Ack": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "NetworkBlockNumber": {
      "description": "BlockNumber",
      "type": "object",
      "properties": {
        "blockNumber": {
          "description": "\u003cb\u003eBlockNumber\u003c/b\u003e",
          "type": "integer"
        }
      }
    },
    "Principal": {
      "type": "string"
    },
    "To": {
      "description": "To address",
      "type": "object",
      "properties": {
        "address": {
          "description": "\u003cb\u003eaddress\u003c/b\u003e",
          "type": "string"
        }
      }
    }
  }
}`))
}
