swagger: "2.0"
info:
  title: Godemo
  version: "0.0.1"
  description: |
    Godemo is a Golang code demo.
produces:
  - application/json
consumes:
  - application/json
schemes:
  - http

basePath: /

paths:
  # Homepage
  /:
    get:
      tags:
        - Homepage
      summary: Homepage
      operationId: homepage
      responses:
        200:
          description: homepage response
          schema:
            $ref: "#/definitions/Ack"
        default:
          description: user validation error
          schema:
            $ref: "#/definitions/Error"
  # Network
  /network/block-number:
    get:
      tags:
        - Network
      summary: Get block number
      operationId: getBlockNumber
      description: <b>Get blockchain block number</b>
      responses:
        200:
          description: block number
          schema:
            $ref: "#/definitions/NetworkBlockNumber"
        default:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"
  # Account
  /account/transfer:
    post:
      tags:
        - Account
      summary: Set a transfer
      operationId: setTransfer
      description: <b>Set a transfer</b>
      responses:
        201:
          description: transfer
          schema:
            $ref: "#/definitions/Ack"
        default:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"
  /account/balance/{address}:
    get:
      tags:
        - Account
      summary: Get account balance
      operationId: getAccountBalance
      description: <b>Get account balance</b>
      parameters:
        - name: "address"
          in: "path"
          description: "address to get balance"
          required: true
          type: string
      responses:
        201:
          description: transfer
          schema:
            $ref: "#/definitions/Ack"
        default:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"

definitions:
  # Network
  NetworkBlockNumber:
    type: object
    description: BlockNumber
    properties:
      blockNumber:
        type: integer
        description: <b>BlockNumber</b>

  # Responses
  Ack:
    type: object
    properties:
      status:
        type: string
      message:
        type: string

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
    required:
      - code
      - message
  Principal:
    type: string
