// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NetworkBlocNumber BlockNumber
//
// swagger:model NetworkBlocNumber
type NetworkBlocNumber struct {

	// <b>BlockNumber</b>
	BlockNumber int64 `json:"blockNumber,omitempty"`
}

// Validate validates this network bloc number
func (m *NetworkBlocNumber) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NetworkBlocNumber) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkBlocNumber) UnmarshalBinary(b []byte) error {
	var res NetworkBlocNumber
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
